// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzpyerfbyyndpcfsnwny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6cHllcmZieXluZHBjZnNud255Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNzI4OTAsImV4cCI6MjA2ODc0ODg5MH0.qZsE1VPhuuTvkHfFqtX_2ibBFcacpLkYE4cj61DTAlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});